spring:
  datasource:
    url: jdbc:mysql://rm-2ze0ugw1914yhx5ja9o.mysql.rds.aliyuncs.com/wikidev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: wikidev
    password: 6141119ZXzgw
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml